site_name: Nethereum
pages: 
- Home: 'index.md'
- Introduction:
    - 'Introduction' : 'introduction/introduction.md'
    - 'Getting started with the Ethereum Client' : 'introduction/ethereum-client.md'
    - 'Web3' : 'introduction/web3.md'
    - 'RPC' : 'introduction/rpc.md'
    - 'IPC' : 'introduction/ipc.md'
- Contracts:
    - 'Step by step writing contracts and deployment' : 'contracts/deploying.md'
    - 'Step by step transactions, events, filters and topics' : 'contracts/calling-transactions-events.md'
- 'Sample Projects' : 'demos/sample-projects.md'
   